### ISSUE TITLE
Department endpoint

### ISSUE THREAD

**Issue by babin17** [babin17/HRM#16]
Api endpoint for department which is assigned to each employee.

**Comment by babin17** [comment]
done

**Comment by babin17** [comment]
This issue is solved

**Comment by babin17** [comment]
use `localhost:5000/department` routes to test and implement

**Comment by babin17** [comment]
@BirajMajhi 
test this and let us @RupeshBasnet12 @babin17 know

**Comment by RupeshBasnet12** [comment]
yes please
